# Generated by Django 2.1 on 2018-10-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
