version: '2'

services:
  webpack:
    build:
      context: .
      dockerfile: Dockerfile.webpack
    volumes_from:
      - webapp:rw

  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    volumes:
      - .:/app
    ports:
      - "8000:8000"
