version: '2'

services:
  webpack:
    build:
      context: .
      dockerfile: Dockerfile.webpack
    depends_on:
      - webapp
    volumes_from:
      - webapp:rw
    command: ls /app

  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    ports:
      - "8000:8000"
