version: '2'

services:
  webpack:
    build:
      context: .
      dockerfile: Dockerfile.webpack
    depends_on:
      - webapp
    volumes_from:
      - webapp:rw
    command: ls /app

  db:
    image: postgres:latest
    ports:
      - "5432"

  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL
